const catalog=[
{id:'f1',type:'film',title:'Lumière sur l’océan',year:2026,genre:'Aventure',duration:'1h 48',rating:4.8,new:true,c1:'#087da9',c2:'#111a42',desc:'Une aventure fictive au large d’un océan immense, entre découverte, entraide et paysages spectaculaires.'},
{id:'f2',type:'film',title:'Le Dernier Voyage',year:2026,genre:'Drame',duration:'1h 52',rating:4.7,new:true,c1:'#7a3d9c',c2:'#19133a',desc:'Un récit fictif sur un voyage inattendu qui change la manière de voir le monde.'},
{id:'f3',type:'film',title:'Un été différent',year:2025,genre:'Comédie',duration:'1h 34',rating:4.5,new:true,c1:'#d37a2e',c2:'#52243f',desc:'Une comédie fictive où un été ordinaire devient une aventure inoubliable.'},
{id:'f4',type:'film',title:'Les Petites Étoiles',year:2025,genre:'Famille',duration:'1h 29',rating:4.6,new:false,c1:'#25736d',c2:'#102b42',desc:'Une histoire familiale fictive pleine de douceur, de rêves et de petites victoires.'},
{id:'f5',type:'film',title:'Au-delà des nuages',year:2024,genre:'Fantastique',duration:'1h 41',rating:4.4,new:false,c1:'#3655a6',c2:'#15183d',desc:'Un monde fantastique fictif où les nuages cachent un passage mystérieux.'},
{id:'f6',type:'film',title:'Le Secret du village',year:2024,genre:'Mystère',duration:'1h 46',rating:4.3,new:false,c1:'#4e7654',c2:'#17221c',desc:'Un mystère fictif dans un village paisible où chacun semble connaître une partie de l’histoire.'},
{id:'f7',type:'film',title:'Planète Horizon',year:2023,genre:'Science-fiction',duration:'2h 02',rating:4.7,new:false,c1:'#235b9a',c2:'#151a36',desc:'Une mission fictive vers une planète lointaine et les choix de son équipage.'},
{id:'f8',type:'film',title:'Le Jardin des rêves',year:2023,genre:'Romance',duration:'1h 38',rating:4.2,new:false,c1:'#b84d70',c2:'#3a1d3e',desc:'Une romance fictive douce autour d’un jardin caché au cœur d’une petite ville.'},
{id:'f9',type:'film',title:'Nos amis les animaux',year:2022,genre:'Documentaire',duration:'1h 16',rating:4.8,new:false,c1:'#3d875b',c2:'#142d26',desc:'Un documentaire fictif consacré aux animaux et aux paysages naturels.'},
{id:'f10',type:'film',title:'Les Aventuriers du dimanche',year:2022,genre:'Animation',duration:'1h 22',rating:4.5,new:false,c1:'#cf6d35',c2:'#243d69',desc:'Une animation fictive pleine d’humour et d’aventures pour toute la famille.'},
{id:'s1',type:'series',title:'Les Carnets du Nord',year:2026,genre:'Documentaire',duration:'6 épisodes',rating:4.9,new:true,c1:'#1b728a',c2:'#102239',desc:'Une série documentaire fictive consacrée aux paysages, métiers et histoires du Nord.'},
{id:'s2',type:'series',title:'Mission Horizon',year:2025,genre:'Science-fiction',duration:'8 épisodes',rating:4.6,new:true,c1:'#7b4b25',c2:'#24172d',desc:'Une équipe fictive part à la recherche d’un horizon que personne n’a encore cartographié.'},
{id:'s3',type:'series',title:'Histoires de famille',year:2025,genre:'Drame',duration:'10 épisodes',rating:4.5,new:true,c1:'#8b3e59',c2:'#2a172d',desc:'Des histoires fictives, humaines et touchantes qui suivent plusieurs générations.'},
{id:'s4',type:'series',title:'La Maison bleue',year:2024,genre:'Comédie',duration:'8 épisodes',rating:4.2,new:false,c1:'#2774a8',c2:'#192a4a',desc:'Une comédie fictive située dans une grande maison où rien ne se passe comme prévu.'},
{id:'s5',type:'series',title:'Les Mondes cachés',year:2024,genre:'Fantastique',duration:'7 épisodes',rating:4.7,new:false,c1:'#6944a6',c2:'#191b42',desc:'Une série fantastique fictive où des portes invisibles apparaissent dans la ville.'},
{id:'s6',type:'series',title:'Petits Défis',year:2023,genre:'Famille',duration:'12 épisodes',rating:4.3,new:false,c1:'#2e8b7a',c2:'#142d3a',desc:'Une série familiale fictive autour de défis, d’amitié et de bonne humeur.'}
];
let favorites=JSON.parse(localStorage.getItem('cinelibre-favorites')||'[]');
const $=id=>document.getElementById(id);
function filtered(){const q=$('searchInput').value.trim().toLowerCase(),type=$('typeFilter').value,genre=$('genreFilter').value,sort=$('sortFilter').value;let list=catalog.filter(x=>(!q||[x.title,x.genre,x.type,x.year].join(' ').toLowerCase().includes(q))&&(type==='all'||x.type===type)&&(genre==='all'||x.genre===genre));if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);if(sort==='title')list.sort((a,b)=>a.title.localeCompare(b.title,'fr'));if(sort==='recent')list.sort((a,b)=>b.year-a.year);return list}
function card(x){const fav=favorites.includes(x.id);return `<article class="card"><div class="poster" style="--c1:${x.c1};--c2:${x.c2}"><span class="badge">${x.type==='film'?'FILM':'SÉRIE'}${x.new?' • NOUVEAU':''}</span><button class="heart ${fav?'active':''}" onclick="toggleFav('${x.id}')">${fav?'♥':'♡'}</button><div class="poster-title">${x.title}</div></div><div class="card-body"><h3>${x.title}</h3><div class="meta"><span>${x.year}</span><span>•</span><span>${x.genre}</span><span>•</span><span class="rating">★ ${x.rating}</span></div><button class="card-btn" onclick="openDetail('${x.id}')">Voir la fiche</button></div></article>`}
function render(){const list=filtered(),films=list.filter(x=>x.type==='film'),series=list.filter(x=>x.type==='series'),news=list.filter(x=>x.new);$('resultCount').textContent=list.length;$('filmCount').textContent=`${films.length} résultat(s)`;$('seriesCount').textContent=`${series.length} résultat(s)`;$('newCards').innerHTML=news.slice(0,5).map(card).join('');$('filmCards').innerHTML=films.map(card).join('');$('seriesCards').innerHTML=series.map(card).join('');const favList=catalog.filter(x=>favorites.includes(x.id));$('favCards').innerHTML=favList.map(card).join('');$('emptyFav').classList.toggle('hidden',favList.length>0);$('favCount').textContent=favorites.length;$('favCount2').textContent=favorites.length}
function toggleFav(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('cinelibre-favorites',JSON.stringify(favorites));render();showToast(favorites.includes(id)?'❤️ Ajouté à ta liste':'Retiré de ta liste')}
function openDetail(id){const x=catalog.find(v=>v.id===id);if(!x)return;const fav=favorites.includes(id);$('detailContent').innerHTML=`<div class="detail"><div class="detail-poster" style="--c1:${x.c1};--c2:${x.c2}">${x.title}</div><div><span class="section-kicker">${x.type==='film'?'FILM':'SÉRIE'}</span><h2>${x.title}</h2><div class="meta">${x.year} • ${x.genre} • ${x.duration} • <span class="rating">★ ${x.rating}</span></div><div class="chips"><span class="chip">Démo CinéLibre</span><span class="chip">Diffusion légale uniquement</span></div><p>${x.desc}</p><p><small>Ce titre est fictif et sert à présenter l’interface. Pour un vrai contenu, le bouton de lecture devra pointer uniquement vers une source dont la diffusion est autorisée.</small></p><button class="btn primary" onclick="showToast('▶ Lecture de démonstration');document.getElementById('detailDialog').close()">▶ Regarder la démo</button> <button class="btn ghost" onclick="toggleFav('${id}');openDetail('${id}')">${fav?'♥ Retirer':'♡ Ajouter'} à ma liste</button></div></div>`;$('detailDialog').showModal()}
function showToast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
['searchInput','typeFilter','genreFilter','sortFilter'].forEach(id=>$(id).addEventListener('input',render));
$('showAllBtn').onclick=e=>{e.preventDefault();$('searchInput').value='';$('typeFilter').value='all';$('genreFilter').value='all';$('sortFilter').value='recent';render();$('films').scrollIntoView({behavior:'smooth'})};
$('menuBtn').onclick=()=>$('nav').classList.toggle('open');
$('closeDialog').onclick=()=>$('detailDialog').close();$('closeAccount').onclick=()=>$('accountDialog').close();$('closeSupport').onclick=()=>$('supportDialog').close();$('accountBtn').onclick=()=>$('accountDialog').showModal();$('supportBtn').onclick=()=>$('supportDialog').showModal();$('demoAccount').onclick=()=>{showToast('👤 Mode démo activé');$('accountDialog').close()};
$('genreTiles').innerHTML=[['⚡','Action'],['😂','Comédie'],['🎭','Drame'],['🚀','Science-fiction'],['✨','Fantastique'],['👨‍👩‍👧','Famille'],['🎨','Animation'],['❤️','Romance'],['🌿','Documentaire'],['🔎','Mystère']].map(([i,g])=>`<button class="genre-tile" onclick="$('genreFilter').value='${g}';render();$('catalogue').scrollIntoView({behavior:'smooth'})"><span class="genre-icon">${i}</span><strong>${g}</strong><small>Explorer</small></button>`).join('');
render();
